### ISSUE TITLE
Contamination column schema overly restrictive?

### ISSUE THREAD

**Issue by stschiff** [poseidon-framework/poseidon-schema#64]
This may be just my current mood in preparing the Gretzinger et al. 2022 package with nearly 500 samples, but I think the fact that the contamination columns have an "all-or-nothing" attitude to it is a bit annoying. Gretzinger et al. supply only point estimates of contamination in their supplement, not errors. In this case I can find out by asking the first author, but often this information may be literally inaccessible.

I would like to suggest to loosen the criteria on the Contamination_* family of columns. Currently, `Contamination`	, `Contamination_Err` and `Contamination_Meas` all have to be filled, or none of them (at least that's I think how `trident validate` validates them). The only column in that family that is optional is `Contamination_Note`.

I would suggest to make them all optional. After all, even an estimate without an error bar would be quite nice for many analyses, and in the end this is anyway hardly a column that is amenable to sophisticated quantitative analyses. It's more of a numeric underpinning of a quality threshold (PASS or FAIL).

**Comment by nevrome** [comment]
My first intuition is strong opposition... But as always I'm happy to be convinced otherwise :slightly_smiling_face:

Making `Contamination` optional: There is no point in having the other Contamination_* columns without this one, right?

Making `Contamination_Err` optional: Enforcing the availability of an error estimate seems reasonable to me to ensure a high quality of information. And to my knowledge the tools typically used to measure ancient DNA contamination do, in fact, provide such an error estimate. But as I'm not an expert I'll ultimately leave the decision to you.

Making `Contamination_Meas` optional: I think it's very important to know how a given measure was obtained.

**Comment by nevrome** [comment]
Sorry for closing and reopening the issue - my hand slipped.

**Comment by stschiff** [comment]
I see your point, and I guess you're right. In the specific case, I just will have to discuss with Joscha what to put. I suspect that there will be sometimes cases where this policy will delay submission of a package, but that's OK as in the end we did opt for high quality standards. OK, I'll close this.
